#Configuration for database
spring:
  application:
    name: social_network
  profiles: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/social_network?serverTimezone=UTC
    username: user
    password: ""
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/social_network?serverTimezone=UTC
    user: user
    password: ""
